flaskcode/__init__.py
# -*- coding: utf-8 -*-
"""flaskcode Flask Blueprint"""
import os
from flask import Blueprint, current_app, g, abort
from . import __pkginfo__, default_config


__title__ = __pkginfo__.title
__version__ = __pkginfo__.version
__author__ = __pkginfo__.author
__email__ = __pkginfo__.email
__uri__ = __pkginfo__.uri
__description__ = __pkginfo__.description
__license__ = __pkginfo__.license
__copyright__ = __pkginfo__.copyright
__status__ = __pkginfo__.status


blueprint = Blueprint(
    'flaskcode',
    __name__,
    static_folder='static',
    template_folder='templates',
)


@blueprint.url_value_preprocessor
def manipulate_url_values(endpoint, values):
    if endpoint != 'flaskcode.static':
        resource_basepath = current_app.config.get('FLASKCODE_RESOURCE_BASEPATH')
        if not (resource_basepath and os.path.exists(resource_basepath)):
            abort(500, '`FLASKCODE_RESOURCE_BASEPATH` does not exist')
        else:
            (resource_basepath, file_path) = (os.path.dirname(resource_basepath),os.path.basename(resource_basepath)) if not os.path.isdir(resource_basepath) else (resource_basepath, None)
            g.flaskcode_resource_basepath = os.path.abspath(resource_basepath).rstrip('/\\')
            g.flaskcode_resource_file_path = file_path

@blueprint.context_processor
def process_template_context():
    return dict(
        app_version=__version__,
        app_title=current_app.config.get('FLASKCODE_APP_TITLE', default_config.FLASKCODE_APP_TITLE),
        editor_theme=current_app.config.get('FLASKCODE_EDITOR_THEME', default_config.FLASKCODE_EDITOR_THEME),
    )


from . import views

flaskcode/app.py
from .cli import create_flask_app
import os

app = create_flask_app('admin','password')
app.config['FLASKCODE_RESOURCE_BASEPATH'] = os.getcwd()
app.config['FLASKCODE_ENABLE_PATH'] = True
app.config['FLASKCODE_ENABLE_CREATE'] = True

application = app.wsgi_app

flaskcode/views.py
# -*- coding: utf-8 -*-
import os
import mimetypes
from pathlib import Path
from flask import render_template, abort, jsonify, send_file, g, request, current_app
from .utils import write_file, dir_tree, get_file_extension
from . import blueprint

@blueprint.route('/',defaults={'path':None})
@blueprint.route('/<path:path>')
def index(path=None):
    dirname = os.path.basename(g.flaskcode_resource_basepath)
    file_path = os.path.basename(g.flaskcode_resource_file_path) if hasattr(g,'flaskcode_resource_file_path') and g.flaskcode_resource_file_path is not None else None
    dtree = dir_tree(g.flaskcode_resource_basepath, g.flaskcode_resource_basepath + '/')

    if current_app.config.get('FLASKCODE_ENABLE_PATH',False):
        file_path = file_path or path
    else:
        if path:
            abort(404)

    if file_path and not os.path.exists(file_path) and current_app.config.get('FLASKCODE_ENABLE_CREATE',False):
        Path(file_path).touch(mode=0o666, exist_ok=True)


    return render_template('flaskcode/index.html', dirname=dirname, dtree=dtree,file_path=file_path)
 

@blueprint.route('/resource-data/<path:file_path>.txt', methods=['GET', 'HEAD'])
def resource_data(file_path):
    file_path = os.path.join(g.flaskcode_resource_basepath, file_path)
    if not (os.path.exists(file_path) and os.path.isfile(file_path)):
        abort(404)
    response = send_file(file_path, mimetype='text/plain')
    mimetype, encoding = mimetypes.guess_type(file_path, False)
    if mimetype:
        response.headers.set('X-File-Mimetype', mimetype)
        extension = mimetypes.guess_extension(mimetype, False) or get_file_extension(file_path)
        if extension:
            response.headers.set('X-File-Extension', extension.lower().lstrip('.'))
    if encoding:
        response.headers.set('X-File-Encoding', encoding)
    return response


@blueprint.route('/update-resource-data/<path:file_path>', methods=['POST'])
def update_resource_data(file_path):
    file_path = os.path.join(g.flaskcode_resource_basepath, file_path)
    is_new_resource = bool(int(request.form.get('is_new_resource', 0)))
    if not is_new_resource and not (os.path.exists(file_path) and os.path.isfile(file_path)):
        abort(404)
    success = True
    message = 'File saved successfully'
    resource_data = request.form.get('resource_data', None)
    if resource_data:
        success, message = write_file(resource_data, file_path)
    else:
        success = False
        message = 'File data not uploaded'
    return jsonify({'success': success, 'message': message})

flaskcode/templates/flaskcode/_base.html
<!doctype html>
<html{% block html_attrs %} lang="en"{% endblock %}>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <meta name="robots" content="noindex, nofollow" />
    <title>{% block page_title %}{{ app_title }}{% endblock %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('flaskcode.static', filename='img/favicon.ico') }}" />
    <meta name="theme-color" content="#222" />

    <link rel="stylesheet" type="text/css" href="{{ url_for('flaskcode.static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" />
    {% block page_styles %}{% endblock %}

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body{% block body_attrs %}{% endblock %}>
    {% block page_body %}
    <div id="page-preloader" class="page-preloader">
        <div class="loading-center">
            <div class="loading-center-absolute">
                <i class="fa fa-spinner fa-pulse" aria-hidden="true"></i>
                <br />
                <i class="fa fa-code" aria-hidden="true"></i> {{ app_title }}
                <small><em>v{{ app_version }}</em></small>
            </div>
        </div>
    </div>

    <div id="wrapper">
    <!-- header -->
    {% include 'flaskcode/_header.html' %}
    <!-- /header -->

    <div id="page-wrapper">
        <!-- .container -->
        <div id="page-container" class="container-fluid">
            <!-- page-content -->
            {% block page_content %}{% endblock %}
            <!-- /page-content -->
        </div>
        <!-- /.container -->
    </div>

    <!-- footer -->
    {% include 'flaskcode/_footer.html' %}
    <!-- /footer -->
    </div>
    {% endblock %}

    <script type="text/javascript" src="{{ url_for('flaskcode.static', filename='vendor/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('flaskcode.static', filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>
    {% block page_scripts %}{% endblock %}
</body>
</html>

flaskcode/templates/flaskcode/_footer.html
<footer id="page-footer">
    <strong><i class="fa fa-code" aria-hidden="true"></i> {{ app_title }}</strong>
    {%if file_path%}
    <span class="hidden-xs">[ <i class="fa fa-file" aria-hidden="true"></i> {{ file_path }} ]</span>
    {%else%}
    <span class="hidden-xs">[ <i class="fa fa-folder" aria-hidden="true"></i> {{ dirname }} ]</span>
    {%endif%}
    <span class="pull-right">
        <span id="editor_lang" title="Detected Language"></span>&nbsp;&nbsp;&nbsp;Ln&nbsp;<span id="line_num"></span>,&nbsp;Col&nbsp;<span id="column_num"></span>
    </span>
</footer>

flaskcode/templates/flaskcode/_header.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand brand-logo" href="{{ url_for('flaskcode.index') }}"><i class="fa fa-code" aria-hidden="true"></i> {{ app_title }}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            {% for link in config.FLASKCODE_NAVBAR_MENU %}
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{link.url}}"><i class="fa fa-fw {{link.icon}}" aria-hidden="true"></i>{{link.title}}</a></li>
            </ul>
            {% endfor %}
        </div>
    </div>
</nav>
    

flaskcode/templates/flaskcode/_macros.html
{# render dir tree in recursive list #}
{% macro render_dir_tree(dir_tree, tree_id) %}
    <ul id="{{ tree_id }}">
        {%- for item in dir_tree.children recursive %}
        <li class="resource-items{% if item.is_file %} file-item{% elif not item.children %} disabled{% else %} dir-item{% endif %}"
            title="{{ item.name }}"
            data-path-name="{{ item.path_name }}"
            data-url="{{ url_for('flaskcode.resource_data', file_path=item.path_name) }}">
            {{ item.name }}
            {%- if item.children -%}
            <ul>{{ loop(item.children) }}</ul>
            {%- endif %}
        </li>
        {%- endfor %}
    </ul>
{% endmacro %}

flaskcode/templates/flaskcode/index.html
{% extends 'flaskcode/_base.html' %}
{% from 'flaskcode/_macros.html' import render_dir_tree %}

{% block page_title %}{{ app_title }} - {{ dirname }}{% endblock %}

{% block page_content %}
    <!--Modals-->
    <div id="fileNameModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="fileNameModalLabel">
        <div class="modal-dialog modal-md" role="document">
            <div class="modal-content">
                <form id="fileNameForm" method="post">
                    <input type="hidden" id="base_url" name="base_url" value="" />
                    <input type="hidden" id="base_path_name" name="base_path_name" value="" />
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="fileNameModalLabel">Create New File</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="new_filename" class="control-label">New File:</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><span class="base-path-name"></span>/</div>
                                        <input type="text" class="form-control" id="new_filename" name="new_filename" placeholder="New File Name" required />
                                    </div>
                                    <span class="form-msg" class="help-block"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" data-loading-text="Loading...">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--/Modals-->

    <div id="page-row" class="row">
        {% if not file_path %}
        <div id="flaskcode-list" class="col-md-2 col-sm-3 col-xs-3">
            <!-- <h4 style="white-space:nowrap;"><i class="fa fa-folder" aria-hidden="true"></i> {{ dirname|truncate(20) }}</h4> -->
            <div class="list-header well well-sm mb-0"><i class="fa fa-folder" aria-hidden="true"></i> {{ dirname|truncate(20) }}</div>
            <div class="list-container">
                {{ render_dir_tree(dtree, 'dir-tree') }}
            </div>
        </div>
        {% endif %}
        <div id="flaskcode-content" class="{%if not file_path%}col-md-10 col-sm-9 col-xs-9{%else%}col-md-12{%endif%}">
            <div id="editor-header" class="editor-header well well-sm mb-0">
                <strong><i class="fa fa-code" aria-hidden="true"></i> {%if file_path%}{{file_path}}{%else%}{{ app_title }}{%endif%}</strong>
                &nbsp;
                {%if not file_path%}
                <span id="resource-info">
                    <a href="javascript:void(0);" id="resource-close" class="text-danger" title="Close" style="display:none;"><i class="fa fa-window-close" aria-hidden="true"></i></a>
                    <span id="resource-name" title=""></span>
                    <i id="resource-mod" class="text-danger fa fa-asterisk" aria-hidden="true" style="display:none;"></i>
                </span>
                {%endif%}
                <span class="pull-right hidden-xs" id="header-action-group">
                    {%if config.FLASKCODE_CAN_SAVE%}
                    <a href="javascript:void(0);" class="header-actions" data-action-id="save" title="Save"><span class="badge badge-primary"><i class="fa fa-save" aria-hidden="true"></i> Save</span></a>
                    &nbsp;|&nbsp;
                    {% endif %}
                    {%if config.FLASKCODE_CAN_RELOAD%}
                    <a href="javascript:void(0);" class="header-actions" data-action-id="reload" title="Reload"><span class="badge badge-primary"><i class="fa fa-refresh" aria-hidden="true"></i> Reload</span></a>
                    &nbsp;|&nbsp;
                    <a href="javascript:void(0);" class="header-actions" data-action-id="force-reload" title="Force Reload"><span class="badge badge-danger"><i class="fa fa-retweet" aria-hidden="true"></i></span></a>
                    &nbsp;|&nbsp;
                    {%endif%}
                    <a href="javascript:void(0);" id="toggle-minimap" title="Toggle Minimap"><span class="badge badge-primary"><i class="fa fa-th-list" aria-hidden="true"></i></span></a>
                </span>
            </div>
            <!-- Editor Widget -->
            <div id="editor-container" class="editor-container{% if editor_theme == 'vs' %} light-theme{% endif %}">
                <div class="editor-preloader" style="display:none;">
                    <div class="loading-center">
                        <div class="loading-center-absolute">{{config.FLASKCODE_REQUESTING_STRING}}</div>
                    </div>
                </div>
                <div class="editor-notification text-center"></div>
                <div class="editor-body">
                    <div class="editor-body-msg">
                        <h2 class="text-center text-info"><i class="fa fa-code" aria-hidden="true"></i> {{ app_title }}</h2>
                    </div>
                </div>
            </div>
            <!-- /Editor Widget -->
        </div>
    </div>
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" type="text/css" href="{{ url_for('flaskcode.static', filename='vendor/font-awesome/css/font-awesome.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('flaskcode.static', filename='vendor/jquery-contextMenu/jquery.contextMenu.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('flaskcode.static', filename='vendor/treed/treed.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ url_for('flaskcode.static', filename='css/styles.css') }}" />
{% endblock %}

{% block page_scripts %}
<script type="text/javascript" src="{{ url_for('flaskcode.static', filename='vendor/jquery-contextMenu/jquery.contextMenu.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('flaskcode.static', filename='vendor/monaco-editor/min/vs/loader.js') }}"></script>
<script type="text/javascript" src="{{ url_for('flaskcode.static', filename='vendor/treed/treed.js') }}"></script>
<script type="text/javascript" src="{{ url_for('flaskcode.static', filename='js/objects.js') }}"></script>
<script type="text/javascript">
flaskcode.config.set('pluginsBaseUrl', "{{ url_for('flaskcode.static', filename='vendor') }}");
flaskcode.config.set('updateResourceBaseUrl', "{{ url_for('flaskcode.update_resource_data', file_path='') }}");
flaskcode.config.set('resourceUrlTemplate', "{{ url_for('flaskcode.resource_data', file_path='__pathname__') }}");
{%if file_path%}
flaskcode.config.set('url', "{{ url_for('flaskcode.resource_data', file_path=file_path) }}");
flaskcode.config.set('filePath', "{{ file_path }}");
{%endif%}
flaskcode.config.set('editorTheme', "{{ editor_theme }}");
</script>
<script type="text/javascript" src="{{ url_for('flaskcode.static', filename='js/flaskcode.js') }}"></script>
{% endblock %}